---
<img src="https://asset.brandfetch.io/idvDrMBg3m/idgDR62lX4.png" alt="Logo Data Rockstars" width="274" height="80">

### 🔒 Le contenu de ce document est confidentiel. 📝
_Le contenu de ce document est confidentiel et la copie ou la distribution est interdite._ 😶‍🌫️

📧 Pour toute question, veuillez nous contacter à [contact@datarockstars.ai](mailto:contact@datarockstars.ai)

---
# Le programme du notebook

**📖 Au programme**
- Cours guidé pour apprendre en s'exerçant
- Exercices avec différents niveaux
- Exercices avancés : pour aller plus loin

**🎁 Les takeaways**
- Accès à la plateforme
- Notebooks
- Snippets penses bêtes de code que vous pouvez garder à vie

---

🔰 Démarrez en exécutant chaque segment de code un à un et en analysant les résultats affichés. 

--- 
A vous de jouer 😎✌️

## 1. Les librairies à importer

In [1]:
# importer numpy
import numpy as np

# afficher la version de numpy
print(np.__version__)

# afficher la configuration de numpy (non nécessaire)
# np.show_config()

import pandas as pd

1.26.4


## 2. Cours

In [3]:
# Manipulation de tableau : Les indexes
arr = np.array([1,2,3,4,5,6])

In [8]:
# Accès à la première valeur du tableau
print(arr[5])

6


In [5]:
# Accès à la dernière valeur du tableau
print(arr[-1])

6


In [9]:
# Accès à une sous-séquence du tableau (éléments aux positions 1, 2 et 3)
print(arr[1:5])

[  2 999   4   5]


In [7]:
# Modification de la valeur à la position 2
arr[2] = 999
print(arr)

[  1   2 999   4   5   6]


#### **Qu'est ce que le slicing ?**
Explication supplémentaire sur le découpage (slicing). <br>
La syntaxe générale pour le découpage est `arr[start:stop:step]`.


*   `start` est l'indice à partir duquel commencer le découpage.
*   `stop` est l'indice jusqu'auquel aller (non inclus).
*   `step` est l'intervalle entre chaque élément à prendre dans le découpage. (ne peux pas être égal à 0)





In [ ]:
# Accès à chaque deuxième élément du tableau - soit prendre un élèment sur 2 en partant du début du tableau
print(arr[::3])

# Explication : start et stop sont omis, ce qui signifie que le découpage couvre tout le tableau/
# Le step est 2, ce qui signifie qu'on prend un élément sur deux.

In [ ]:
# Création d'un tableau NumPy à partir d'une liste Python
list = [1, 2, 3, 4, 5]
numpy_array = np.array(list)
print(numpy_array)

In [ ]:
# Création d'un tableau 2D (aussi appelé matrice) en utilisant des listes imbriquées
multi_dim_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(multi_dim_array)

In [ ]:
# Utilisation de la propriété shape pour obtenir la forme (dimensions) du tableau
print(multi_dim_array.shape)

In [ ]:
# Accès à un élément spécifique du tableau en utilisant l'indexation
print(multi_dim_array[1, 2])  # Accès à l'élément à la première ligne, deuxième colonne

In [ ]:
# Création d'un tableau rempli de zéros
zeros = np.zeros((3, 3))
print(zeros)

In [ ]:
# Création d'un tableau rempli de uns
ones = np.ones((3, 3))
print(ones)

In [ ]:
# Création d'une matrice identité (diagonale de uns, le reste est zéro)
identity = np.eye(3)
print(identity)

In [ ]:
# Démonstration de certaines opérations mathématiques de base sur les tableaux
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)

In [ ]:
# Utilisation de fonctions universelles (ufunc) pour effectuer des opérations sur les tableaux
print(np.sqrt(array1))
print(np.log(array1))
print(np.exp(array1))

In [ ]:
# Modification de la forme d'un tableau sans changer ses données avec la méthode reshape
reshaped_array = array1.reshape((3, 1))
print(reshaped_array)

In [ ]:
# Create a sample 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a border filled with 0's around the array
border_width = 1  # Width of the border
padded_arr = np.pad(arr, pad_width=border_width, mode='constant', constant_values=0)

# Print the padded array
print(padded_arr)

In [ ]:
# Tri d'un tableau
unsorted_array = np.array([2, 1, 5, 3, 7, 4])
sorted_array = np.sort(unsorted_array)
print(sorted_array)

## 3. Exercices - Niveau : ★☆☆

In [12]:
# Exercice 1 : Créer un vecteur avec des valeurs allant de 10 à 49.

nom_vec = np.arange(10,50)
print(nom_vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


<details>
    <summary> Avoir un indice 🕵️ </summary>

<p>
<pre>
Utilisez la fonction np.arange(a,b)
</pre>
</details>

<details>
    <summary> Voir la réponse 🔮 </summary>

<p>
<pre>
mon_vecteur = np.arange(10,51) # création du vecteur
mon_vecteur # display
</pre>
</details>

In [13]:
#  Exercice 2 : Créer une matrice 3x3 avec des valeurs allant de 0 à 8.
vecteur = np.arange(0, 9)
matrice = vecteur.reshape(3, 3)
print(matrice)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<details>
    <summary> Avoir un indice 🕵️ </summary>

<p>
<pre>
Utilisez la fonction reshape
</pre>
</details>

<details>
    <summary> Voir la réponse 🔮 </summary>

<p>
<pre>
ma_matrice = np.arange(9).reshape(3, 3)
ma_matrice
</details>

In [14]:
# Exercice 3 : Créer une matrice 3D 3x3x3 avec des valeurs aléatoires.
ma_matrice_random = np.random.random((3,3,3))
ma_matrice_random

array([[[0.86334372, 0.11216878, 0.48722497],
        [0.71769483, 0.36281831, 0.5223579 ],
        [0.89540119, 0.92389215, 0.49159015]],

       [[0.91318035, 0.70646627, 0.30153547],
        [0.45698307, 0.8947351 , 0.37067353],
        [0.94277357, 0.55981497, 0.46418991]],

       [[0.24182675, 0.25608201, 0.41376492],
        [0.21084356, 0.64358108, 0.47169671],
        [0.38880909, 0.81300433, 0.44042491]]])

<details>
    <summary> Avoir un indice 🕵️ </summary>

<p>

Utilisez a fonction `np.random.random((a,b,c))`

</details>

<details>
    <summary> Voir la réponse 🔮 </summary>

<p>
<pre>
ma_matrice_random = np.random.random((3,3,3))
ma_matrice_random
</details>

## 3. Exercices - Niveau : ★★☆


In [19]:
# Exercice : Créez un tableau numpy 256x256 dont les valeurs varient linéairement sur l'axe des x pour créer un effet de gradient.

gradient = np.linspace(0, 1, 256)
gradient_rep = np.tile(gradient, (256, 1))
print(gradient_rep)

[[0.         0.00392157 0.00784314 ... 0.99215686 0.99607843 1.        ]
 [0.         0.00392157 0.00784314 ... 0.99215686 0.99607843 1.        ]
 [0.         0.00392157 0.00784314 ... 0.99215686 0.99607843 1.        ]
 ...
 [0.         0.00392157 0.00784314 ... 0.99215686 0.99607843 1.        ]
 [0.         0.00392157 0.00784314 ... 0.99215686 0.99607843 1.        ]
 [0.         0.00392157 0.00784314 ... 0.99215686 0.99607843 1.        ]]


<details>
    <summary> Indice 🕵️ </summary>
<p>

Pour créer un tableau numpy 256x256 avec un effet de gradient, vous pouvez utiliser la fonction np.linspace pour générer une ligne de valeurs de 0 à 1, puis utiliser np.tile pour répéter cette ligne 256 fois.
</details>
<details>
    <summary> Voir la réponse 🔮 </summary>
<p>
<pre>
# Solution
gradient = np.linspace(0, 1, 256)
image_gradient = np.tile(gradient, (256, 1))
Afficher le tableau
plt.imshow(image_gradient)
plt.show()
</pre>

</details>

## 3. Exercices - Niveau : ★★★

**Etape 1  :** Récupérer les données d'entraînement du dataset Titanic (dans le dossier data) et chargez les informations dans un dataframe. Affichez les 5 premières et les 5 dernières lignes.

In [20]:
# Votre code
df = pd.read_csv("data/train.csv")
df.head()
df.tail()


PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

<details>
    <summary> Indice 🕵️ </summary>
<p>

Pensez à utiliser la fonction `df.head()` pour afficher les cinq premières lignes et `df.tail()` pour afficher les cinq dernières lignes.

</details>
<details>
    <summary> Voir la réponse 🔮 </summary>
<p>
<pre>
#Ouverture du CSV
df = pd.read_csv("data/train.csv", sep=",")

#Affichage des cinq premières lignes
df.head()

#Affichage des cinq dernières lignes
df.tail()
</pre>
</details>